### ISSUE TITLE
BUG: When stopping a service that doesn't start and other service depend on (pending), when starting other services keep pending

### ISSUE THREAD

**Issue by alonisser** [uditalias/swamp#40]
for example: service A , service B depends on A
service A is starting, B is pending
service A fails to start because of  a bug, B is pending
force stop service A, B is pending (Maybe should be stopped now?)
fix the bug, start A

B is still pending..

**Comment by uditalias** [comment]
fixed

now when service is in the factor loop, when the service started successfully the start phase will continue, if the user chose to stop a `STARTING` service, all other `PENDING` services will be stopped too

available from v0.0.25
